#!/usr/bin/env node
// Generates per-tool command directories and MCP configs from the canonical
// sources in commands/ and mcp/servers.json.
//
// Edit commands/*.md and mcp/servers.json only — everything this script writes
// is overwritten on the next run.
//
//   node build.mjs                        regenerate all targets
//   node build.mjs --check                exit 1 if any target is stale (CI)
//   node build.mjs --lint                 validate canonical sources only
//   node build.mjs --with playwright,ctx7 also emit these opt-in MCP servers

import { readFileSync, writeFileSync, readdirSync, mkdirSync, rmSync, existsSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const root = dirname(fileURLToPath(import.meta.url));
const SRC = join(root, "commands");
const argv = process.argv.slice(2);
const check = argv.includes("--check");
const lintOnly = argv.includes("--lint");

// --with playwright,context7  |  --with=playwright,context7
const withArg = (() => {
  const eq = argv.find((a) => a.startsWith("--with="));
  if (eq) return eq.slice("--with=".length);
  const i = argv.indexOf("--with");
  return i !== -1 ? argv[i + 1] : "";
})();
const extras = withArg ? withArg.split(",").map((s) => s.trim()).filter(Boolean) : [];

// This marker appears in every generated file. Cleanup only ever deletes files
// that carry it, so a consumer's own hand-written commands are never touched.
const MARKER = "GENERATED by build.mjs";
const banner = (file) => `${MARKER} from ${file} — do not edit by hand.`;

const die = (msg) => { console.error(`error: ${msg}`); process.exit(1); };

// --- frontmatter -------------------------------------------------------------

const REQUIRED = ["name", "description"];

/** Minimal frontmatter split. Returns { attrs, body }. */
function parse(raw, file) {
  const m = raw.match(/^---\r?\n([\s\S]*?)\r?\n---\r?\n([\s\S]*)$/);
  if (!m) die(`${file}: missing YAML frontmatter`);
  const attrs = {};
  for (const line of m[1].split(/\r?\n/)) {
    const kv = line.match(/^([A-Za-z][\w-]*):\s*(.*)$/);
    // Strip surrounding quotes only when they match — "foo' is a typo, not a quoted string.
    if (kv) attrs[kv[1]] = kv[2].trim().replace(/^(["'])(.*)\1$/, "$2");
  }
  for (const key of REQUIRED) {
    if (!attrs[key]) die(`${file}: frontmatter is missing required key \`${key}\``);
  }
  // Normalise line endings so ^...$ anchors and byte comparison behave the same
  // on a CRLF checkout as on LF.
  return { attrs, body: m[2].replace(/\r\n/g, "\n").trim() };
}

const yamlStr = (s) => `"${String(s).replace(/\\/g, "\\\\").replace(/"/g, '\\"')}"`;

/**
 * Resolve {{INCLUDE:_partial.md}} against commands/_*.md.
 * Partials may include other partials; a cycle is a build error.
 */
function expandIncludes(body, file, seen = []) {
  return body.replace(/^[ \t]*\{\{INCLUDE:([A-Za-z0-9_.-]+)\}\}[ \t]*$/gm, (_match, name) => {
    if (!name.startsWith("_")) die(`${file}: {{INCLUDE:${name}}} — partials must start with an underscore`);
    if (seen.includes(name)) die(`${file}: circular include ${[...seen, name].join(" → ")}`);
    const path = join(SRC, name);
    if (!existsSync(path)) die(`${file}: {{INCLUDE:${name}}} — commands/${name} does not exist`);
    const partial = readFileSync(path, "utf8").replace(/\r\n/g, "\n").trim();
    // Replacement is a function so $&, $1 etc. inside a partial stay literal.
    return expandIncludes(partial, name, [...seen, name]);
  });
}

// --- command targets ---------------------------------------------------------
// Each target renders one canonical command into one tool's dialect.
// Frontmatter must start at byte 0 or the host tool won't parse it, so for
// frontmatter targets the banner goes inside the block as a YAML comment.
const targets = [
  {
    name: "claude-code",
    dir: join(root, ".claude", "commands"),
    render: ({ attrs, body, file }) => {
      const fm = [`# ${banner(file)}`, `description: ${yamlStr(attrs.description)}`];
      if (attrs["argument-hint"]) fm.push(`argument-hint: ${yamlStr(attrs["argument-hint"])}`);
      return `---\n${fm.join("\n")}\n---\n\n${body}\n`;
    },
  },
  {
    name: "opencode",
    dir: join(root, ".opencode", "commands"),
    render: ({ attrs, body, file }) => {
      // opencode supports: description, agent, model, subtask. No argument-hint —
      // fold the hint into the description so the TUI still shows expected args.
      const desc = attrs["argument-hint"]
        ? `${attrs.description} — args: ${attrs["argument-hint"]}`
        : attrs.description;
      return `---\n# ${banner(file)}\ndescription: ${yamlStr(desc)}\n---\n\n${body}\n`;
    },
  },
  {
    name: "cursor",
    dir: join(root, ".cursor", "commands"),
    render: ({ attrs, body, file }) =>
      `---\n# ${banner(file)}\ndescription: ${yamlStr(attrs.description)}\n---\n\n${body}\n`,
  },
  {
    name: "portable",
    dir: join(root, "prompts"),
    // No frontmatter, no tool-specific tokens: paste into anything.
    render: ({ attrs, body, file }) =>
      `<!-- ${banner(file)} -->\n# ${attrs.name}\n\n> ${attrs.description}\n>\n> Portable copy-paste version. Replace \`{{ARGUMENTS}}\` below with your input` +
      (attrs["argument-hint"] ? ` (${attrs["argument-hint"]}).` : ".") +
      `\n\n---\n\n${body.replace(/\$ARGUMENTS/g, "{{ARGUMENTS}}")}\n`,
  },
];

// --- MCP targets -------------------------------------------------------------
// One canonical roster in mcp/servers.json → three tool dialects. Hand-editing
// three files is what let .cursor/mcp.json go missing in the first place.

function loadServers() {
  const path = join(root, "mcp", "servers.json");
  if (!existsSync(path)) return {};
  const all = JSON.parse(readFileSync(path, "utf8"));
  const out = {};
  for (const [name, spec] of Object.entries(all)) {
    if (name.startsWith("$")) continue;
    if (spec.profile === "default" || extras.includes(name)) out[name] = spec;
  }
  for (const name of extras) {
    if (!(name in out)) die(`--with ${name}: no such server in mcp/servers.json`);
  }
  return out;
}

const stdio = (s) => s.transport === "stdio";

// Headers are how the GitHub server takes both its credential and its toolset
// filter. `${VAR}` is expanded by the host agent at load time, so a token is
// never written into a generated file.
const hdrs = (s) => (s.headers && Object.keys(s.headers).length ? { headers: s.headers } : {});

const mcpTargets = [
  {
    name: "claude-code-mcp",
    file: join(root, ".mcp.json"),
    render: (servers) => {
      const mcpServers = {};
      for (const [n, s] of Object.entries(servers)) {
        mcpServers[n] = stdio(s)
          ? { type: "stdio", command: s.command, args: s.args ?? [] }
          : { type: "http", url: s.url, ...hdrs(s) };
      }
      return JSON.stringify({ mcpServers }, null, 2) + "\n";
    },
  },
  {
    name: "cursor-mcp",
    file: join(root, ".cursor", "mcp.json"),
    render: (servers) => {
      const mcpServers = {};
      for (const [n, s] of Object.entries(servers)) {
        // Cursor infers stdio from the presence of `command`; no `type` key.
        mcpServers[n] = stdio(s) ? { command: s.command, args: s.args ?? [] } : { url: s.url, ...hdrs(s) };
      }
      return JSON.stringify({ mcpServers }, null, 2) + "\n";
    },
  },
  {
    name: "opencode-mcp",
    file: join(root, "opencode.json"),
    // opencode.json is a full user-facing config file, so patch the `mcp` key
    // in place and preserve everything else the user has put there.
    render: (servers, current) => {
      const base = current ? JSON.parse(current) : { $schema: "https://opencode.ai/config.json" };
      const mcp = {};
      for (const [n, s] of Object.entries(servers)) {
        // opencode takes a single `command` array, not command + args.
        mcp[n] = stdio(s)
          ? { type: "local", command: [s.command, ...(s.args ?? [])], enabled: true }
          : { type: "remote", url: s.url, enabled: true, ...hdrs(s) };
      }
      base.mcp = mcp;
      return JSON.stringify(base, null, 2) + "\n";
    },
  },
];

// --- lint --------------------------------------------------------------------

function lint(files) {
  let problems = 0;
  const fail = (msg) => { console.error(`lint: ${msg}`); problems++; };

  for (const file of files) {
    const raw = readFileSync(join(SRC, file), "utf8");
    const { attrs, body } = parse(raw, file);

    if (attrs.name !== file.replace(/\.md$/, "")) {
      fail(`${file}: frontmatter name \`${attrs.name}\` does not match the filename`);
    }
    if (attrs.description.length > 200) {
      fail(`${file}: description is ${attrs.description.length} chars (max 200)`);
    }
    if (body.includes("$ARGUMENTS") && !attrs["argument-hint"]) {
      fail(`${file}: body uses $ARGUMENTS but frontmatter has no argument-hint`);
    }
    if (!body.includes("$ARGUMENTS") && attrs["argument-hint"]) {
      fail(`${file}: declares argument-hint but never reads $ARGUMENTS`);
    }
    if (body.includes("{{ARGUMENTS}}")) {
      fail(`${file}: contains {{ARGUMENTS}} — canonical sources use $ARGUMENTS, the portable target rewrites it`);
    }
    if (body.includes(MARKER)) {
      fail(`${file}: contains the generated-file marker — you are editing a build output, not a source`);
    }
    if (body.includes("{{BOOTSTRAP}}")) {
      fail(`${file}: {{BOOTSTRAP}} was replaced by {{INCLUDE:_bootstrap.md}}`);
    }
    // Resolves partials and dies on a missing or circular include.
    expandIncludes(body, file);
  }

  const path = join(root, "mcp", "servers.json");
  if (existsSync(path)) {
    let all;
    try { all = JSON.parse(readFileSync(path, "utf8")); }
    catch (e) { fail(`mcp/servers.json: invalid JSON — ${e.message}`); all = {}; }
    for (const [name, s] of Object.entries(all)) {
      if (name.startsWith("$")) continue;
      if (!["default", "opt-in"].includes(s.profile)) fail(`mcp/servers.json: ${name} has invalid profile \`${s.profile}\``);
      if (!["http", "stdio"].includes(s.transport)) fail(`mcp/servers.json: ${name} has invalid transport \`${s.transport}\``);
      if (s.transport === "http" && !s.url) fail(`mcp/servers.json: ${name} is http but has no url`);
      if (s.transport === "stdio" && !s.command) fail(`mcp/servers.json: ${name} is stdio but has no command`);
      if (!s.why) fail(`mcp/servers.json: ${name} has no \`why\` — every server must justify its token cost`);
    }
  }

  if (problems) { console.error(`\n${problems} lint problem(s)`); process.exit(1); }
  console.log(`lint: ${files.length} command(s) ok`);
}

// --- build -------------------------------------------------------------------

const files = readdirSync(SRC, { withFileTypes: true })
  .filter((d) => d.isFile() && d.name.endsWith(".md") && !d.name.startsWith("_"))
  .map((d) => d.name)
  .sort();
if (!files.length) die("commands/ contains no command files");

lint(files);
if (lintOnly) process.exit(0);

let stale = 0;
let written = 0;

const report = (label, isStale) => {
  if (isStale) { console.error(`stale: ${label}`); stale++; }
};

for (const target of targets) {
  // Clear out commands that no longer exist upstream. Only ever delete files we
  // generated — a consumer running this in their own repo must keep their own
  // slash commands, and prompts/README.md must survive.
  if (existsSync(target.dir)) {
    for (const d of readdirSync(target.dir, { withFileTypes: true })) {
      if (!d.isFile() || !d.name.endsWith(".md") || files.includes(d.name)) continue;
      const path = join(target.dir, d.name);
      if (!readFileSync(path, "utf8").includes(MARKER)) continue; // not ours
      if (check) report(`${target.name}/${d.name} (no longer in commands/)`, true);
      else rmSync(path);
    }
  } else if (!check) {
    mkdirSync(target.dir, { recursive: true });
  }

  for (const file of files) {
    const parsed = parse(readFileSync(join(SRC, file), "utf8"), file);
    parsed.body = expandIncludes(parsed.body, file);

    const out = target.render({ ...parsed, file });
    const dest = join(target.dir, file);
    const current = existsSync(dest) ? readFileSync(dest, "utf8") : null;

    if (current === out) continue;
    if (check) { report(`${target.name}/${file}`, true); continue; }
    writeFileSync(dest, out);
    written++;
  }
}

const servers = loadServers();
for (const target of mcpTargets) {
  if (!existsSync(dirname(target.file)) && !check) mkdirSync(dirname(target.file), { recursive: true });
  const current = existsSync(target.file) ? readFileSync(target.file, "utf8") : null;
  const out = target.render(servers, current);
  if (current === out) continue;
  if (check) { report(target.name, true); continue; }
  writeFileSync(target.file, out);
  written++;
}

const names = Object.keys(servers).join(", ") || "none";

if (check) {
  if (stale) { console.error(`\n${stale} file(s) out of date — run \`node build.mjs\``); process.exit(1); }
  console.log("all targets up to date");
} else {
  console.log(
    `built ${files.length} command(s) → ${targets.map((t) => t.name).join(", ")}` +
      `\nmcp servers: ${names}` +
      `\n${written} file(s) changed`,
  );
}
