#!/usr/bin/env node
// Generates per-tool command directories from the canonical sources in commands/.
// Edit commands/*.md only — everything this script writes is overwritten on the next run.
//
//   node build.mjs           regenerate all targets
//   node build.mjs --check   exit 1 if any target is stale (for CI)

import { readFileSync, writeFileSync, readdirSync, mkdirSync, rmSync, existsSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const root = dirname(fileURLToPath(import.meta.url));
const SRC = join(root, "commands");
const check = process.argv.includes("--check");

// Frontmatter must start at byte 0 or the host tool won't parse it, so for
// frontmatter targets the banner goes inside the block as a YAML comment.
const banner = (file) => `GENERATED by build.mjs from commands/${file} — do not edit by hand.`;

/** Minimal frontmatter split. Returns { attrs, body }. */
function parse(raw, file) {
  const m = raw.match(/^---\r?\n([\s\S]*?)\r?\n---\r?\n([\s\S]*)$/);
  if (!m) throw new Error(`${file}: missing YAML frontmatter`);
  const attrs = {};
  for (const line of m[1].split(/\r?\n/)) {
    const kv = line.match(/^([A-Za-z][\w-]*):\s*(.*)$/);
    if (kv) attrs[kv[1]] = kv[2].trim().replace(/^["'](.*)["']$/, "$1");
  }
  return { attrs, body: m[2].trim() };
}

const yamlStr = (s) => `"${String(s).replace(/"/g, '\\"')}"`;

// --- targets -----------------------------------------------------------------
// Each target renders one canonical command into one tool's dialect.
const targets = [
  {
    name: "claude-code",
    dir: join(root, ".claude", "commands"),
    render: ({ attrs, body, file }) => {
      const fm = [`# ${banner(file)}`, `description: ${attrs.description}`];
      if (attrs["argument-hint"]) fm.push(`argument-hint: ${yamlStr(attrs["argument-hint"])}`);
      return `---\n${fm.join("\n")}\n---\n\n${body}\n`;
    },
  },
  {
    name: "opencode",
    dir: join(root, ".opencode", "commands"),
    render: ({ attrs, body, file }) => {
      // opencode supports: description, agent, model, subtask. No argument-hint —
      // fold the hint into the description so the TUI still shows expected args.
      const desc = attrs["argument-hint"]
        ? `${attrs.description} — args: ${attrs["argument-hint"]}`
        : attrs.description;
      return `---\n# ${banner(file)}\ndescription: ${yamlStr(desc)}\n---\n\n${body}\n`;
    },
  },
  {
    name: "cursor",
    dir: join(root, ".cursor", "commands"),
    render: ({ attrs, body, file }) =>
      `---\n# ${banner(file)}\ndescription: ${yamlStr(attrs.description)}\n---\n\n${body}\n`,
  },
  {
    name: "portable",
    dir: join(root, "prompts"),
    // No frontmatter, no tool-specific tokens: paste into anything.
    render: ({ attrs, body, file }) =>
      `<!-- ${banner(file)} -->\n# ${attrs.name}\n\n> ${attrs.description}\n>\n> Portable copy-paste version. Replace \`{{ARGUMENTS}}\` below with your input` +
      (attrs["argument-hint"] ? ` (${attrs["argument-hint"]}).` : ".") +
      `\n\n---\n\n${body.replace(/\$ARGUMENTS/g, "{{ARGUMENTS}}")}\n`,
  },
];

// --- build -------------------------------------------------------------------
const files = readdirSync(SRC).filter((f) => f.endsWith(".md") && !f.startsWith("_"));
if (!files.length) throw new Error("commands/ contains no command files");

const bootstrap = readFileSync(join(SRC, "_bootstrap.md"), "utf8").trim();

let stale = 0;
let written = 0;

for (const target of targets) {
  // Clear out commands that no longer exist upstream, but never touch sibling
  // files in that directory (.claude/settings.local.json, etc).
  if (existsSync(target.dir)) {
    for (const f of readdirSync(target.dir)) {
      if (f.endsWith(".md") && !files.includes(f)) {
        if (check) { console.error(`stale: ${target.name}/${f} (no longer in commands/)`); stale++; }
        else rmSync(join(target.dir, f));
      }
    }
  } else if (!check) {
    mkdirSync(target.dir, { recursive: true });
  }

  for (const file of files) {
    const parsed = parse(readFileSync(join(SRC, file), "utf8"), file);
    parsed.body = parsed.body.replace(
      /^\{\{BOOTSTRAP\}\}$/m,
      parsed.attrs.bootstrap === "false" ? "" : bootstrap,
    );

    const out = target.render({ ...parsed, file });
    const dest = join(target.dir, file);
    const current = existsSync(dest) ? readFileSync(dest, "utf8") : null;

    if (current === out) continue;
    if (check) { console.error(`stale: ${target.name}/${file}`); stale++; continue; }
    writeFileSync(dest, out);
    written++;
  }
}

if (check) {
  if (stale) { console.error(`\n${stale} file(s) out of date — run \`node build.mjs\``); process.exit(1); }
  console.log("all targets up to date");
} else {
  console.log(
    `built ${files.length} command(s) → ${targets.map((t) => t.name).join(", ")}` +
      ` (${written} file(s) changed)`,
  );
}
